Factory/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models {
  public class FactoryContextFactory: IDesignTimeDbContextFactory < FactoryContext > {

    FactoryContext IDesignTimeDbContextFactory < FactoryContext > .CreateDbContext(string[] args) {
      IConfigurationRoot configuration = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("appsettings.json")
        .Build();

      var builder = new DbContextOptionsBuilder < FactoryContext > ();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Factory.Models {
  public class Engineer {
    public Engineer() {
      this.JoinEntities = new HashSet < EngineerMachine > ();
    }

    public int EngineerId {get; set;}
    public string Name {get; set;}
    public virtual ICollection < EngineerMachine > JoinEntities {get; set;}
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models {
  public class EngineerMachine {
    public int EngineerMachineId {get; set;}
    public int MachineId {get; set;}
    public int EngineerId {get; set;}
    public virtual Machine Machine {get; set;}
    public virtual Engineer Engineer {get; set;}
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models {
  public class FactoryContext: DbContext {
    public DbSet <Engineer> Engineers {get; set;}
    public DbSet <Machine> Machines {get; set;}
    public DbSet <EngineerMachine> EngineerMachine {get; set;}

    public FactoryContext(DbContextOptions options): base(options) {}

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models {
  public class Machine {
    public Machine() {
      this.JoinEntities = new HashSet < EngineerMachine > ();
    }

    public int MachineId {get; set;}
    public string Name {get; set;}

    public virtual ICollection < EngineerMachine > JoinEntities {
      get;
    }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers {
  public class EngineersController: Controller {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db) {
      _db = db;
    }

    public ActionResult Index() {
      List < Engineer > model = _db.Engineers.ToList();
      return View(model);
    }

    public ActionResult Create() {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer Engineer) {
      _db.Engineers.Add(Engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id) {
      var thisEngineer = _db.Engineers
        .Include(Engineer => Engineer.JoinEntities)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(Engineer => Engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer Engineer) {
      _db.Entry(Engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id) {
      var thisEngineer = _db.Engineers.FirstOrDefault(Engineer => Engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id) {
      var thisEngineer = _db.Engineers.FirstOrDefault(Engineer => Engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
          public ActionResult Edit(int id) {
      var thisEngineer = _db.Engineers.FirstOrDefault(Engineer => Engineer.EngineerId == id);
      return View(thisEngineer);
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Factory.Controllers {
  public class HomeController: Controller {

    [HttpGet("/")]
    public ActionResult Index() {
      return View();
    }

  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers {
  public class MachinesController: Controller {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db) {
      _db = db;
    }

    public ActionResult Index() {
      return View(_db.Machines.ToList());
    }

    public ActionResult Create() {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine Machine, int EngineerId) {
      _db.Machines.Add(Machine);
      _db.SaveChanges();
      if (EngineerId != 0) {
        _db.EngineerMachine.Add(new EngineerMachine() {
          EngineerId = EngineerId, MachineId = Machine.MachineId
        });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id) {
      var thisMachine = _db.Machines
        .Include(Machine => Machine.JoinEntities)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(Machine => Machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id) {
      var thisMachine = _db.Machines.FirstOrDefault(Machine => Machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine Machine, int EngineerId) {
      if (EngineerId != 0) {
        _db.EngineerMachine.Add(new EngineerMachine() {
          EngineerId = EngineerId, MachineId = Machine.MachineId
        });
      }
      _db.Entry(Machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id) {
      var thisMachine = _db.Machines.FirstOrDefault(Machine => Machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id) {
      var thisMachine = _db.Machines.FirstOrDefault(Machine => Machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id) {
      var thisMachine = _db.Machines.FirstOrDefault(Machine => Machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine Machine, int EngineerId) {
      if (EngineerId != 0) {
        _db.EngineerMachine.Add(new EngineerMachine() {
          EngineerId = EngineerId, MachineId = Machine.MachineId
        });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId) {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/Create.cshtml
@{
Layout = "_Layout";
}

@model Factory.Models.Engineer

<h3>add an engineer</h3>
<hr>
@using (Html.BeginForm())
{
<label for="Name">name: </label>
  <input type=text id="Name" name="Name" placeholder="new name here" class="form-control" style="width:300px;" autocomplete="off" required>
  <br>
  <input type="submit" value="add" class="btn btn-primary"/>
}

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h3>delete engineer "@Html.DisplayFor(model => model.Name)"?</h3>
<hr>

@using (Html.BeginForm())
{
  <input type="submit" value="delete" class="btn btn-danger"/>
}

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h3>@Html.DisplayFor(model => model.Name) (engineer) details</h3>
<hr/>
@if(@Model.JoinEntities.Count == 0)
{
  <p>this engineer does not maintain any machines.</p>
}
else
{
  <h4>machines mantained:</h4>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Machine.Name</li>
  }
}
<hr/>
<p>@Html.ActionLink("edit", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("delete", "Delete", new { id = Model.EngineerId })</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h3>edit "@Html.DisplayFor(model => model.Name)" (engineer)</h3>
<hr>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

<label for="Name">name: </label>
  <br>
  <input type=text id="Name" name="Name" placeholder="new name here" class="form-control" style="width:300px;" value="@Html.DisplayFor(model => model.Name)" autocomplete="off" required>
  <br>
  <input type="submit" value="save" class="btn btn-primary"/>
}

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h1>👨‍🔧 engineers</h1>
<hr>
@if (@Model.Count == 0)
{
  <p>no engineers have been added yet</p>
} 
  @foreach(Engineer Engineer in Model)
  {
    <li>@Html.ActionLink($"{Engineer.Name}", "Details", new { id = Engineer.EngineerId })</li>
  }
<hr>
<p>@Html.ActionLink("+", "Create")</p>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>welcome to the factory 🏭</h1>
<hr>
<p>@Html.ActionLink("see all machines", "Index", "Machines")</p> <p>@Html.ActionLink("see all engineers", "Index", "Engineers")</p>

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3>assign a new engineer to @Html.DisplayFor(model => model.Name)</h3>
<hr>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)
    <label for="EngineerId">engineer:</label>
    @Html.DropDownList("EngineerId", null, new { @class="form-control", @style="width:300px"})
<br>
    <input type="submit" value="save" class="btn btn-primary"/>
}

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3>add a new machine</h3>
<hr>

@using (Html.BeginForm())
{
  <label for="Name">name: </label>
  <input type=text id="Name" name="Name" placeholder="new name here" class="form-control" style="width:300px;" autocomplete="off" required>
<br>
    <label for="EngineerId">engineer:</label>
    @Html.DropDownList("EngineerId", null, new { @class="form-control", @style="width:300px"})
    <br>
  <input type="submit" value="add" class="btn btn-primary" />
}

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3>delete machine "@Html.DisplayFor(model => model.Name)"?</h3>
<hr>

@using (Html.BeginForm())
{
  <input type="submit" value="delete" class="btn btn-danger"/>
}

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine
<h3>@Html.DisplayFor(model => model.Name) (machine) details</h3>
<hr />

@if(@Model.JoinEntities.Count == 0)
{
  <p>@Html.DisplayFor(model => model.Name) is not repaired by any engineers</p>
}

  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Engineer.Name</li>
    @using (Html.BeginForm("DeleteEngineer", "Machines"))
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
      <input type="submit" value="delete" class="btn btn-danger"/>
    }
  }
<hr>
<p>@Html.ActionLink("add an engineer", "AddEngineer", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("edit", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("delete", "Delete", new { id = Model.MachineId })</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3>edit "@Html.DisplayFor(model => model.Name)" (Machine)</h3>
<hr>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

<label for="Name">name: </label>
  <br>
  @* @Html.EditorFor(model => model.Name) *@
  <input type=text id="Name" name="Name" placeholder="new name here" class="form-control" style="width:300px;" value="@Html.DisplayFor(model => model.Name)" autocomplete="off" required>
  <br>
  <input type="submit" value="save" class="btn btn-primary"/>
}

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<h1>🤖 machines</h1>
<hr>
@if (@Model.Count == 0)
{
  <p>no machines have been added yet</p>
} 

@foreach (Machine Machine in Model)
{
  <li>@Html.ActionLink($"{Machine.Name}", "Details", new { id = Machine.MachineId })</li>
}
<hr>
<p>@Html.ActionLink("+", "Create")</p>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <title>Factory</title>
      <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🤖</text></svg>">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <link rel="stylesheet" href="~/css/styles.css">
   </head>
   <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
         <div class="container">
            <a class="navbar-brand" href="/">🏭</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
               <ul class="navbar-nav">
                  <li class="nav-item active">
                     <a class="nav-link" href="/">factory <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="/Engineers">👨‍🔧 engineers</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="/Machines">🤖 machines</a>
                  </li>
               </ul>
            </div>
         </div>
      </nav>
      <div class="container">
         @RenderBody()
      </div>
   </body>
</html>